### ISSUE TITLE
iOS login crash

### ISSUE THREAD

**Issue by PixelEnvision** [jizc/CloudOnce#12]
Hi I don't have exact steps yet but it looks like CloudOnce is not working properly with the latest Unity.

Issue I'm seeing is, my build cannot always initialise could save and load the values. It can connect sometimes but it cannot at the next run. It's not stable as I've seen few crashes too referencing to IL2CPP code.

Game Center seems to be able to connect every time. I'll try falling back to 5.5.1f1 & 5.5.0 today. Same code it was working fine with latest 5.4 patch release.

I just wanted to ask if you've experienced something similar before.

Best regards,
Erdener

--
### Environment

- CloudOnce __v2.3.3__
- Unity3D __v5.5.1p4__v5.5.2f1
- Build platform: iOS

**Comment by jizc** [comment]
I have not had any issues, but I haven't tested the newest Unity version yet. I'll look into it.

**Comment by PixelEnvision** [comment]
Thank you for your prompt reply.

I'm trying with 5.5.1f1 and behaviour is the same but I've noticed the following: I'm seeing welcome banner of the game center (& over is working too) but CouldOnce still logs it as failed and it's not loading the cloud data which is the next step.

Failed to sign in to Apple Game Center.
CloudOnce.Internal.Providers.<SignIn>c__AnonStorey0:<>m__0(Boolean)

I think some how CouldOnce completes the check before game center login is complete. Could that be the case?

I'll try to disable auto cloud load & call it manually in OnInitializeComplete.

**Comment by jizc** [comment]
For iOS CloudOnce uses Unitys built-in Game Center support. The "Failed to sign in to Apple Game Center." debug log is part of the callback from the `Social.localUser.Authenticate` method. So if the callback is actually being called too soon, that is a bug in Unity.

I appreciate any additional info you can discover, as I don't have easy access to an iOS test environment at the moment.

**Comment by PixelEnvision** [comment]
I think that really is the case as it was working fine with 5.4.x.

I've disabled "Auto Sign In" & "Auto Cloud Load" on the Initialize script and called them seperately as follows:
	public void InitializeComplete ()
	{
		Cloud.SignIn (false);
		Cloud.Storage.Load ();
	}

That seems to be fixed it, so far it's working OK with all my attempts.

**Comment by jizc** [comment]
I have a possible workaround for you.

In Unity 5.5 they added an overload to the `Social.localUser.Authenticate` method. This overload has a different callback (Action<bool, string> instead of Action<bool>), so my theory is that in Unity 5.5 this new callback may function properly, while the old one is broken.

So I've committed a new version of `iOSCloudProvider` that uses the new callback when running on Unity 5.5 or newer. You can get it here: [iOSCloudProvider](https://github.com/jizc/CloudOnce/blob/46ab84a9e8f9dc7a2a8165d2133805cbe9fb5b02/source/PluginDev/Assets/Extensions/CloudOnce/Providers/AppleGameCenter/iOSCloudProvider.cs).

It would be awesome if you could test this workaround for me. Just replace the `iOSCloudProvider` file in your project with this new one.

BTW, I found [this](https://issuetracker.unity3d.com/issues/ios-calling-social-dot-localuser-dot-authenticate-crashes-in-string-memcpy2-m2338403668) on the Unity Issue Tracker. Does it look like the problem you are experiencing?

**Comment by PixelEnvision** [comment]
I've just tried that, logged in & loaded cloud data but ended up with a crash on my first run.

![crash](https://cloud.githubusercontent.com/assets/8680071/23331824/ae2eef44-fb65-11e6-9a7f-a40529fdbc14.jpg)

It didn't crash on the second run, but it could not see the login again.

Crash does look similar but it's not the same I think.

**Comment by PixelEnvision** [comment]
I gave it a 3rd run before reverting back and ended up with a different crash, again after login & receiving cloud data.

![crash2](https://cloud.githubusercontent.com/assets/8680071/23331854/3c2bfb8e-fb66-11e6-8980-a3d7b0c5db29.jpg)

**Comment by PixelEnvision** [comment]
Ah, hold on a bit more plz. My mistake, I couldn't test with the right file.

I'll re-try & post back shortly.

**Comment by jizc** [comment]
The two crashes you posted are actually the same crash, as you can see both stack traces end with `AchievementWrapper loadAchievements`.

I'm not certain if this is from an internal Unity call that is part of the `Authenticate` method, or if it's from CloudOnce loading the achievements after a successful login.

You can test this by commenting out [line 181](https://github.com/jizc/CloudOnce/blob/46ab84a9e8f9dc7a2a8165d2133805cbe9fb5b02/source/PluginDev/Assets/Extensions/CloudOnce/Providers/AppleGameCenter/iOSCloudProvider.cs#L181) in the new version of `iOSCloudProvider` (`UpdateAchievementsData();`). This will make sure that CloudOnce doesn't attempt to load the achiements. If that solves the crash there is a bug in CloudOnce, if not, the bug is most likely in Unity.

**Comment by PixelEnvision** [comment]
In both cases crash happened after GC sign-in & receiving cloud data. So, achievements theory makes sense. I'll try that and let you know...

And the test result with the new file, it's the same before. It can still miss the login and thinks it's failed.

My workaround was still working last time I've tried, I'll try it again now...

Btw, I'm back to 5.5.2f1

**Comment by jizc** [comment]
In [this crash](https://cloud.githubusercontent.com/assets/8680071/23331854/3c2bfb8e-fb66-11e6-8980-a3d7b0c5db29.jpg) I now see the `UpdateAchievementsData` method is actually listed as line 8 of the stack trace. So it definitely appears to be where the problem is. I'll do some research.

**Comment by jizc** [comment]
The cause might be the use of `System.Linq` within the `Social.LoadAchievements` callback, as I've experienced crashes on iOS before due to the use of Linq. I'll rewrite the method and get back to you.

**Comment by PixelEnvision** [comment]
Thank you. My current state is as follows with 5.5.2 & new iOSCloudProvider file with UpdateAchievementsData() commented out + using my workaround.

* No crashes so far.
* Cloud load works every time.
* Cloud save doesn't seems to be working. I'll check if that's because sign-in status.

**Comment by PixelEnvision** [comment]
I've placed a call to Cloud.SignIn (false) in OnSignInFailed callback.

So there is a new crash righ after calling this: UnityEngine.SocialPlatforms.GameCenter.GameCenterPlatform:AuthenticateCallbackWrapper(Int32, String)

I'm not sure if it's because of a loop or forcing it or something missing from the call...

**Comment by PixelEnvision** [comment]
![crash3](https://cloud.githubusercontent.com/assets/8680071/23332284/fa6811e8-fb6e-11e6-943e-407354148839.jpg)
if that helps..

**Comment by jizc** [comment]
Thanks for the update. I've uploaded a new version of `iOSCloudProvider` [here](https://github.com/jizc/CloudOnce/blob/ab483b888de68a43137869236f1101630977a2e6/source/PluginDev/Assets/Extensions/CloudOnce/Providers/AppleGameCenter/iOSCloudProvider.cs) that doesn't rely on Linq. I hope it helps! Calling `Cloud.SignIn(false)` should have no effect when called from a `OnSignInFailed` callback, because the `isSigningIn` field in `iOSCloudProvider` will still be `true` at that point, making the `SignIn` method ignore the call.

**Comment by PixelEnvision** [comment]
I see, thank you I'll try the new file now. On another note:

* Cloud init enabled just with cloud save as before.
* I've called Cloud.Storage.Load in OnInitializeComplete callback
* No call to Cloud.SignIn at launch.

What happens:
- Game loads cloud data just fine.
- Cloud save also seems to be working fine.
- When I tap leader boards it complains not signed in and starts sign-in sequence
- Crash after sign-in failure

![crash4](https://cloud.githubusercontent.com/assets/8680071/23332398/eef17e6a-fb70-11e6-83f2-4e1125b3c18b.jpg)

**Comment by jizc** [comment]
That latest crash looks like it might be caused by attempting to `Debug.Log` the string part of the Authenticate callback. I added a null check that might help. New version: [iOSCloudProvider](https://github.com/jizc/CloudOnce/blob/10e422a25357bebef3220d4bef21caa1823c3c46/source/PluginDev/Assets/Extensions/CloudOnce/Providers/AppleGameCenter/iOSCloudProvider.cs)

**Comment by PixelEnvision** [comment]
Thanks, unfortunately it didn't help with the crash. But you were right about the Debug.Log, I've turned off debug mode and it's not crashing anymore.

I'll try going back to original setup now, initializing all 3 option with the script without any custom calls...

**Comment by PixelEnvision** [comment]
Current state with all the updates: Login authentication is still not working correctly. That new workaround seems to be working ok, cloud data loaded & saved, GC logged in (even if it's reported not)

![settings](https://cloud.githubusercontent.com/assets/8680071/23332944/5dd95600-fb7a-11e6-9885-96877003a193.jpg)

and that callback

	void InitializeComplete ()
	{
		Cloud.Storage.Load ();
	}

**Comment by jizc** [comment]
Thanks for the update. Just to clarify, are you saying that the game still crashes if you enable all three toggles on the initialization settings?

**Comment by PixelEnvision** [comment]
No, I haven't seen a crash after disabling the debug log.

If I enable all three toggles, game center authentication still logged as false most of the time (about 9 out 10) which is in effect causing not loading of cloud data.

Above setup forces it load, since GC is actually logged in it seems to be working.

**Comment by jizc** [comment]
Ah, OK. Thanks for the tip about sign in failure causing cloud load to not work. Cloud loading is not dependent on Game Center (only iCloud), so I have now changed it so that load is called regardless of the outcome of the GC authentication. Here is [yet another version of iOSCloudProvider](https://github.com/jizc/CloudOnce/blob/74d0c99fe893aa8a0e822a7e8648d50a648977ce/source/PluginDev/Assets/Extensions/CloudOnce/Providers/AppleGameCenter/iOSCloudProvider.cs).

Still don't know why the authentication is failing so much, but I believe that may be out of my control, and may be an issue with Unity 5.5. I'm glad you at least now have a functional workaround.

**Comment by PixelEnvision** [comment]
Ah, that should do it. Thank you for all of your time & help.

I agree, that seems to be 5.5 issue with Social.localUser.Authenticate as it's not failing every time. I've already submitted a bug report, I hope it get's noticed...

**Comment by PixelEnvision** [comment]
Hello again for a Sunday night update... I've pushed the build to TestFlight and ended up with a crash again detailed as follows:

1. Build downloaded & installed from TF
2. App launched
3. Crashes right after GC login banner
4. Immediately re-launched
5. Get's past GC banner this time and any after that
6. Delete the app & go back to step 1 for a crash.

Btw, same build was working fine when pushed to the device from Xcode.

Currently I've re-implemented your old suggestion and commented out (UpdateAchievementsData();) and that seems to fix the crash for the next TF build.

So, I thought I should let you know.

**Comment by PixelEnvision** [comment]
Got a reply from Unity after submitting a repo case.

We're currently working on this issue. This issue causes crash in some cases. It's because we're pushing an integer instead of a string. So it's essentially becoming a random number.
You can track the original case here: https://issuetracker.unity3d.com/issues/ios-calling-social-dot-localuser-dot-authenticate-crashes-in-string-memcpy2-m2338403668

**Comment by jizc** [comment]
Great that they already know what the problem is! I guess we can look forward to a fix before long then.

**Comment by orbitalnine** [comment]
I'm using the latest version of iOSCloudProvider but I still get crashes inside UpdateAchievementData occassionally (say 1 in 5 times).

![screen shot 2017-03-10 at 3 47 10 pm](https://cloud.githubusercontent.com/assets/26336740/23817605/2e6a6ce0-05a9-11e7-8ea2-d025d5bb3214.png)

As well I get the RaiseExecutionEngineExceptionIfMethodNotFound error, though I imagine that is caused by the Unity bug.

**Comment by jizc** [comment]
The crash appears to be within Unity's `Social.LoadAchievements` method. If so, it's a bug in Unity and outside of my control. However, I've made some small tweaks to the `UpdateAchievementsData` method that will hopefully make it even clearer where the crash happens. New version: [iOSCloudProvider](https://github.com/jizc/CloudOnce/blob/6b90f6c62ad85805fa3655e5ffbda7db1fb43c7a/source/PluginDev/Assets/Extensions/CloudOnce/Providers/AppleGameCenter/iOSCloudProvider.cs)

**Comment by orbitalnine** [comment]
With this change, and because Social.LoadAchievements is asynchronous, won't the call to LoadAchievements complete and then you'll iterate on an empty achievements list, then some time later the callback will be sent?

**Comment by jizc** [comment]
Ah, it's been too long since I've worked on this. You are correct. I don't know what else there is to do about this, except filing a bug report with Unity and hope for a fix.

**Comment by orbitalnine** [comment]
Since the crash is inside il2cpp code for a string equals operation it seems like this line causes it to crash:
"if (unifiedAchievement.Value.ID == achievement.id)"

I'm guessing there is something bad with achievement.id that Unity is returning with their callback.

**Comment by jizc** [comment]
Oh I see, I was reading the call stack backwards. Thanks for the tip! I'll try to add some extra checks of both `achievement` and `achievement.id`.

**Comment by jizc** [comment]
I've reverted the last change and added more checks: [iOSCloudProvider](https://github.com/jizc/CloudOnce/blob/76892694c75e02773e81bd7cb83350a3c4c14703/source/PluginDev/Assets/Extensions/CloudOnce/Providers/AppleGameCenter/iOSCloudProvider.cs)

The fact that these checks are needed points to there being a bug in Unity, but hopefully these changes will at least avoid the crash.

**Comment by orbitalnine** [comment]
So I put in some debug statements and the crash I get is actually on unifiedAchievement.Value.ID

- I check if achievement is null, it's not.
- I print out achievement.id, it looks good.
- I check if unifiedAchievement.Value is null, it's not
- I check if unifiedAchievement.Value.ID is null, it's not
- I print out unifiedAchievement.Value.ID, crash on the Debug.Log call, while trying to concat my prefix string and the value, inside String_t::get_length_0()

Since UnifiedAchievement.ID is just a C# string I doubt the problem is in your code. It's more of a blind guess, but it seems like something bad is going inside the c++ version of the LoadAchievement callback function and memory is being corrupted.

I've changed my game to not depend on the results from LoadAchievements, so I'm going to comment the call to UpdateAchievementData for now until I see that Unity has fixed the sign in problem and then test again. If you don't have a test environment, remind me if you see that Unity has fixed the problem in case I miss it.

**Comment by jizc** [comment]
Thanks for the update and additional info @orbitalnine. My guess would be that there is a problem with IL2CPP, related to the reflection code in `UpdateAchievementsData`. I could probably come up with a different solution that doesn't require reflection. Putting it on my to-do list.

**Comment by jizc** [comment]
I've made the changes to the [2.3.4 branch](https://github.com/jizc/CloudOnce/tree/2.3.4). Since several files had to be changed I went ahead and created a new unitypackage file in the `current-build` folder.

I removed both the reflection code and the call to the new overload of `Authenticate`, since it seems to be buggy. I think there is a good chance that this will fix the problem.

I am unable to test this potential fix on an iOS device, so I'll hold off on merging it to the master branch. @orbitalnine, I would really appreciate it if you have a chance to test this fix and get back to me with the results.

**Comment by orbitalnine** [comment]
Sure, I'll test this out shortly and get back to you.

**Comment by orbitalnine** [comment]
I see the same error. The property "All" is not generated in the Achievements class.

**Comment by jizc** [comment]
Ah, that's true that previously generated `Achievement` classes will not have that List. But it should regenerate the class with the `All` field if you make a change to the some achievement, save, undo the change and save again. At least in my tests the code generation worked correctly.

**Comment by jizc** [comment]
OK, I've now upgraded one of my own pre 2.3.4 projects. I had the same issue, but there is a fairly easy workaround.

1. Switch Unity's build target to "PC, Mac & Linux Standalone"
2. Import the new CloudOnce package
3. Save the configuration in the CloudOnce Editor
4. Switch back to whichever build target you were on before

If you still have the new version imported already, it should be enough to just switch to standalone, save, and then switch back.

The reason `All` is not generated is that the compilation error is preventing Unity from importing all the new CloudOnce files. Switching to Standalone is just a way of temporarily removing the compilation error.
